//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLITEModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string productName { get; set; }
        public string vendorName { get; set; }
        public Nullable<long> totalQuantitySold { get; set; }
        public Nullable<decimal> totalIncomes { get; set; }
        public Nullable<long> taxId { get; set; }
        public long justID { get; set; }
        public Nullable<long> ProductID { get; set; }
    
        public virtual Tax Tax { get; set; }
    }
}
