#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using MySQLModule.Model;

namespace MySQLModule.Model	
{
	public partial class Product
	{
		private int _idProducts;
		public virtual int IdProducts
		{
			get
			{
				return this._idProducts;
			}
			set
			{
				this._idProducts = value;
			}
		}
		
		private string _productName;
		public virtual string ProductName
		{
			get
			{
				return this._productName;
			}
			set
			{
				this._productName = value;
			}
		}
		
		private int _vendors_idVendors;
		public virtual int Vendors_idVendors
		{
			get
			{
				return this._vendors_idVendors;
			}
			set
			{
				this._vendors_idVendors = value;
			}
		}
		
		private int _measures_idMeasures;
		public virtual int Measures_idMeasures
		{
			get
			{
				return this._measures_idMeasures;
			}
			set
			{
				this._measures_idMeasures = value;
			}
		}
		
		private decimal? _basePrice;
		public virtual decimal? BasePrice
		{
			get
			{
				return this._basePrice;
			}
			set
			{
				this._basePrice = value;
			}
		}
		
		private Measure _measure;
		public virtual Measure Measure
		{
			get
			{
				return this._measure;
			}
			set
			{
				this._measure = value;
			}
		}
		
		private Vendor _vendor;
		public virtual Vendor Vendor
		{
			get
			{
				return this._vendor;
			}
			set
			{
				this._vendor = value;
			}
		}
		
	}
}
#pragma warning restore 1591
